### ISSUE TITLE
URL Formatierung für die Denkmaldatenbank hat sich geändert

### ISSUE THREAD

**Issue by Dignusss** [plepe/ogd-wikimedia-osm-checker#16]
Bsp: Von https://www.berlin.de/landesdenkmalamt/denkmale/liste-karte-datenbank/denkmaldatenbank/daobj.php?obj_dok_nr=09020354 zu https://denkmaldatenbank.berlin.de/daobj.php?obj_dok_nr=09020354

**Comment by plepe** [comment]
Hmm, that address does not work for me. I get a warning about a self-signed certificate, and if I accept that, I get a 404 error. Also, with http this link does not work. It could be a temporary problem though, so I'll try later again.

**Comment by plepe** [comment]
Vorher getestet, es geht jetzt. Darum hab ich die neue Version jetzt gepusht!
7c8de66f8d9392e2e3c31f6e3da41147f1fd56f2
